name: Require Checklist
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  require-checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: true  # Ensure a checklist is present
